#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys

import matplotlib.pyplot as plt


def read_swc(filename):
    nodes = {}
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            # 忽略空行和注释行
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) != 7:
                print(f"警告：行格式不正确，已忽略：{line}")
                continue
            n = int(parts[0])
            T = int(parts[1])
            x = float(parts[2])
            y = float(parts[3])
            z = float(parts[4])
            radius = float(parts[5])  # 将R重命名为radius
            P = int(float(parts[6]))
            nodes[n] = {'n': n, 'T': T, 'x': x, 'y': y, 'z': z, 'radius': radius, 'P': P, 'children': []}
    # 构建子节点列表
    for node in nodes.values():
        P = node['P']
        if P != -1 and P in nodes:
            nodes[P]['children'].append(node['n'])
        elif P != -1:
            print(f"警告：父节点{P}不存在，节点{node['n']}的父节点设为-1")
            node['P'] = -1
    return nodes

def write_swc(filename, nodes):
    with open(filename, 'w') as f:
        # 可在文件头添加注释
        f.write("# 标准化后的SWC文件\n")
        for n in sorted(nodes.keys()):
            node = nodes[n]
            f.write(f"{node['n']} {node['T']} {node['x']} {node['y']} {node['z']} {node['radius']} {node['P']}\n")

def write_marker(filename, markers):
    with open(filename, 'w') as f:
        # 写入marker文件头
        f.write("# Marker file generated by standardize_swc.py\n")
        f.write("# n x y z radius\n")
        for marker in markers:
            f.write(f"{marker['n']} {marker['x']} {marker['y']} {marker['z']} {marker['radius']}\n")


def read_swc(filename):
    nodes = {}
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            # 忽略空行和注释行
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) != 7:
                print(f"警告：行格式不正确，已忽略：{line}")
                continue
            n = int(parts[0])
            T = int(parts[1])
            x = float(parts[2])
            y = float(parts[3])
            z = float(parts[4])
            radius = float(parts[5])  # 将R重命名为radius
            P = int(float(parts[6]))
            nodes[n] = {'n': n, 'T': T, 'x': x, 'y': y, 'z': z, 'radius': radius, 'P': P, 'children': []}
    # 构建子节点列表
    for node in nodes.values():
        P = node['P']
        if P != -1 and P in nodes:
            nodes[P]['children'].append(node['n'])
        elif P != -1:
            print(f"警告：父节点{P}不存在，节点{node['n']}的父节点设为-1")
            node['P'] = -1
    return nodes

def compute_node_degrees(nodes):
    # 计算每个节点的度（连接数）
    for node in nodes.values():
        degree = len(node['children'])
        if node['P'] != -1:
            degree += 1  # 加上父节点
        node['degree'] = degree


def find_potential_soma(nodes):
    # 计算每个节点的度数
    compute_node_degrees(nodes)

    max_degree = -1
    potential_soma = None

    # 遍历节点，找到度数最大的节点作为潜在soma
    for node in nodes.values():
        if node['degree'] > max_degree:
            max_degree = node['degree']
            potential_soma = node

    # 返回潜在soma的坐标
    if potential_soma:
        return (potential_soma['x'], potential_soma['y'], potential_soma['z'])
    else:
        return None  # 如果没有找到，返回 None
def compute_node_degrees(nodes):
    """计算每个节点的度（连接数）"""
    for node in nodes.values():
        degree = len(node['children'])
        if node['P'] != -1:
            degree += 1  # 加上父节点
        node['degree'] = degree


def find_potential_soma(nodes):
    """基于度数、距离和半径的综合评分，识别最有可能的soma节点"""
    # 计算质心
    x_avg = sum(node['x'] for node in nodes.values()) / len(nodes)
    y_avg = sum(node['y'] for node in nodes.values()) / len(nodes)
    z_avg = sum(node['z'] for node in nodes.values()) / len(nodes)

    # 计算节点的度、距离和半径，并生成评分
    max_score = -1
    potential_soma = None
    for node in nodes.values():
        # 计算节点的度数
        node['degree'] = len(node['children']) + (1 if node['P'] != -1 else 0)

        # 计算节点与质心的欧式距离
        dx = node['x'] - x_avg
        dy = node['y'] - y_avg
        dz = node['z'] - z_avg
        node['distance'] = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5

        # 计算节点的评分，结合度数、距离和半径
        # 假设半径值越大可能性越高，因此将半径作为一个放大因子
        score = (node['degree'] * node['radius']) / (1 + node['distance'])

        # 更新评分最高的节点
        if score > max_score:
            max_score = score
            potential_soma = node['n']

    # if potential_soma:
    #     return (potential_soma['x'], potential_soma['y'], potential_soma['z'])
    # else:
    #     return None  # 如果没有找到，返回 None

    return potential_soma


# def adjust_soma_and_roots(nodes):
#     # 重新识别正确的胞体节点
#     soma_node = find_potential_soma(nodes)
#     print(f"选择节点 {soma_node} 作为胞体节点")
#     nodes[soma_node]['T'] = 1
#     nodes[soma_node]['P'] = -1
#     # 清空胞体节点的子节点列表，重新构建
#     nodes[soma_node]['children'] = []
#     # 将所有其他父节点为 -1 的节点连接到新的胞体节点
#     for node in nodes.values():
#         if node['P'] == -1 and node['n'] != soma_node:
#             node['P'] = soma_node
#             nodes[soma_node]['children'].append(node['n'])
#             print(f"节点 {node['n']} 的父节点设为胞体节点 {soma_node}")
#         elif node['P'] == soma_node and node['n'] != soma_node:
#             nodes[soma_node]['children'].append(node['n'])
#     return soma_node  # 返回胞体节点编号
def find_nearest_connected_node(node, nodes, soma_node):
    """查找与给定节点最近的已连接节点"""
    min_distance = float('inf')
    nearest_node = None
    for other in nodes.values():
        if other['n'] != node['n'] and other['n'] != soma_node and other['P'] != -1:
            dx = node['x'] - other['x']
            dy = node['y'] - other['y']
            dz = node['z'] - other['z']
            distance = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
            if distance < min_distance:
                min_distance = distance
                nearest_node = other['n']
    return nearest_node

def adjust_soma_and_roots(nodes):
    """重新识别正确的胞体节点并连接结构"""
    soma_node = find_potential_soma(nodes)
    print(f"选择节点 {soma_node} 作为胞体节点")
    nodes[soma_node]['T'] = 1
    nodes[soma_node]['P'] = -1
    nodes[soma_node]['children'] = []

    for node in nodes.values():
        if node['P'] == -1 and node['n'] != soma_node:
            # 如果节点的连接没有其他上级，且不直接属于soma，则保留连接关系
            if nodes[soma_node].get('children'):
                # 将其连接到最近的节点，而不是直接连接到soma
                nearest_connected = find_nearest_connected_node(node, nodes, soma_node)
                if nearest_connected:
                    node['P'] = nearest_connected
                    nodes[nearest_connected]['children'].append(node['n'])
            else:
                # 正常连接到soma
                node['P'] = soma_node
                nodes[soma_node]['children'].append(node['n'])
            print(f"节点 {node['n']} 的父节点设为胞体节点 {soma_node}")
    return soma_node  # 返回胞体节点编号


def prune_small_branches(nodes, min_branch_length, soma_node):
    # 标记需要删除的节点及其深度
    nodes_to_delete = []
    # 遍历所有节点，查找末端节点
    for node_id in list(nodes.keys()):
        node = nodes[node_id]
        # 跳过胞体节点及其直接连接的节点
        if node_id == soma_node or node['P'] == soma_node:
            continue
        if len(node['children']) == 0:
            # 开始跟踪分支
            branch_nodes = [(node_id, 0)]  # 存储 (节点ID, 深度)
            current_node_id = node_id
            branch_length = 0
            depth = 0
            while True:
                parent_id = nodes[current_node_id]['P']
                if parent_id == -1 or parent_id == soma_node:
                    break
                dx = nodes[current_node_id]['x'] - nodes[parent_id]['x']
                dy = nodes[current_node_id]['y'] - nodes[parent_id]['y']
                dz = nodes[current_node_id]['z'] - nodes[parent_id]['z']
                branch_length += (dx**2 + dy**2 + dz**2) ** 0.5
                current_node_id = parent_id
                depth += 1
                branch_nodes.append((current_node_id, depth))
                if len(nodes[parent_id]['children']) > 1:
                    break  # 到达分叉点
            # 如果分支长度小于阈值，标记删除
            if branch_length < min_branch_length:
                nodes_to_delete.extend(branch_nodes)
    # 根据深度降序排序，先删除叶子节点
    nodes_to_delete.sort(key=lambda x: x[1], reverse=True)
    # 删除标记的节点
    for node_id, _ in nodes_to_delete:
        if node_id in nodes:
            parent_id = nodes[node_id]['P']
            if parent_id != -1 and parent_id in nodes and node_id in nodes[parent_id]['children']:
                nodes[parent_id]['children'].remove(node_id)
            del nodes[node_id]
    print(f"已删除 {len(nodes_to_delete)} 个节点")


def remove_cycles(nodes):
    # 检测并消除循环，使用迭代的DFS
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    visited = set()
    stack = [(soma_node, set())]  # Stack elements are (node_id, ancestors)
    while stack:
        node_id, ancestors = stack.pop()
        if node_id in visited:
            continue
        visited.add(node_id)
        if node_id in ancestors:
            print(f"检测到循环：节点{node_id}在其祖先中出现")
            # 断开循环，将该节点连接到胞体
            nodes[node_id]['P'] = soma_node
            nodes[soma_node]['children'].append(node_id)
            continue
        ancestors.add(node_id)
        for child_id in nodes[node_id]['children'][:]:
            stack.append((child_id, ancestors.copy()))
        ancestors.remove(node_id)

def correct_node_types(nodes):
    # 根据连接关系校正节点类型
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    stack = [(soma_node, 1)]  # Stack elements are (node_id, parent_type)
    visited = set()
    while stack:
        node_id, parent_type = stack.pop()
        if node_id in visited:
            continue
        visited.add(node_id)
        node = nodes[node_id]
        if node['n'] == soma_node:
            node['T'] = 1  # 胞体节点
        else:
            if node['P'] == soma_node:
                node['T'] = 3  # 直接连接到胞体的节点设为树突（类型3）
            else:
                node['T'] = parent_type
        for child_id in node['children']:
            stack.append((child_id, node['T']))

def visualize_swc(swc_file,ax):
    nodes = []
    with open(swc_file, 'r') as file:
        for line in file:
            if line.startswith('#') or line.strip() == '':
                continue  # 跳过注释和空行
            parts = line.split()
            node_id = int(parts[0])
            x = float(parts[2])
            y = float(parts[3])
            z = float(parts[4])
            parent_id = int(parts[6])
            nodes.append((node_id, x, y, z, parent_id))

            # 创建一个节点字典以便快速查找
    node_dict = {node[0]: node for node in nodes}

            # 绘制每个节点和父节点之间的连接
    for node in nodes:
        node_id, x, y, z, parent_id = node
        if parent_id == -1:
            continue  # 跳过根节点
                # 获取父节点坐标
        parent = node_dict.get(parent_id)
        if parent is not None:
            parent_x, parent_y, parent_z = parent[1], parent[2], parent[3]
            # 绘制连接线
            ax.plot([x, parent_x], [y, parent_y], 'k-', lw=1)

            # 设置绘图样式
    ax.set_aspect('equal')
    ax.axis('off')


def ensure_connected(nodes):
    # 确保所有节点都连接到胞体
    soma_nodes = [node for node in nodes.values() if node['T'] == 1]
    if not soma_nodes:
        print("错误：未找到胞体节点")
        return
    soma_node = soma_nodes[0]  # 假设只有一个胞体节点
    soma_id = soma_node['n']

    # 使用深度优先搜索（DFS）找到所有与胞体节点连通的节点
    connected_nodes = set()
    stack = [soma_id]
    while stack:
        current_node_id = stack.pop()
        if current_node_id in connected_nodes:
            continue
        connected_nodes.add(current_node_id)
        current_node = nodes[current_node_id]
        # 添加子节点到栈中
        for child_id in current_node['children']:
            stack.append(child_id)
        # 添加父节点到栈中（如果存在）
        parent_id = current_node['P']
        if parent_id != -1 and parent_id in nodes:
            stack.append(parent_id)

    # 找到未连接到胞体的节点
    unconnected_nodes = set(nodes.keys()) - connected_nodes

    # 删除未连接到胞体的孤立点（没有父节点和子节点），且与胞体节点距离大于25
    for node_id in list(unconnected_nodes):
        node = nodes[node_id]
        dx = node['x'] - soma_node['x']
        dy = node['y'] - soma_node['y']
        dz = node['z'] - soma_node['z']
        distance = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
        if (node['P'] == -1 and len(node['children']) == 0) or (node['P'] == -1 and distance>25):
            # 计算与胞体节点的距离
            # dx = node['x'] - soma_node['x']
            # dy = node['y'] - soma_node['y']
            # dz = node['z'] - soma_node['z']
            # distance = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
            # if distance > 25:
                # 删除节点
                del nodes[node_id]
                print(f"已删除未连接到胞体且距离超过25的孤立点 {node_id}")
            # else:
            #     # 保留距离小于等于25的孤立点
            #     print(f"保留与胞体距离 {distance:.2f} 的孤立点 {node_id}")
        else:
            # 保留未连接但有父节点或子节点的节点
            pass





def standardize_swc(input_file, output_file, marker_file, min_branch_len):
    nodes = read_swc(input_file)
    if not nodes:
        print("错误：无法读取SWC文件或文件为空")
        return
    soma_node = adjust_soma_and_roots(nodes)
    prune_small_branches(nodes, min_branch_length=min_branch_len, soma_node=soma_node)
    remove_cycles(nodes)
    correct_node_types(nodes)
    # rebuild_children_lists(nodes)
    ensure_connected(nodes)  # 调用修改后的函数
    remove_cycles(nodes)
    write_swc(output_file, nodes)
    #print(f"规范化后的SWC文件已保存至：{output_file}")
    # 收集所有父节点为胞体节点的节点信息
    reparented_nodes = []
    for node in nodes.values():
        if node['P'] == -1:
            # 修改 reparented_nodes 的字段名
            reparented_nodes.append({'n': node['n'], 'x': node['x'], 'y': node['y'], 'z': node['z'], 'radius': node['radius']})
    if reparented_nodes:
        #write_marker(marker_file, reparented_nodes)
        print(f"父节点为胞体节点的节点信息已保存至：{marker_file}")
    else:
        print("没有父节点为胞体节点的节点，未生成marker文件。")


# def ensure_connected(nodes):
#     # 确保所有节点都连接到胞体
#     soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
#     visited = set()
#     stack = [soma_node]
#     while stack:
#         node_id = stack.pop()
#         if node_id in visited:
#             continue
#         visited.add(node_id)
#         for child_id in nodes[node_id]['children']:
#             stack.append(child_id)
#     # 查找未访问的节点
#     for node_id in list(nodes.keys()):
#         if node_id not in visited:
#             print(f"节点 {node_id} 未连接到胞体，修正其父节点为胞体")
#             nodes[node_id]['P'] = soma_node
#             nodes[soma_node]['children'].append(node_id)
#
# def standardize_swc(input_file, output_file, marker_file,min_branch_len):
#     nodes = read_swc(input_file)
#     if not nodes:
#         print("错误：无法读取SWC文件或文件为空")
#         return
#     soma_node = adjust_soma_and_roots(nodes)
#     prune_small_branches(nodes, min_branch_length=min_branch_len, soma_node=soma_node)
#     remove_cycles(nodes)
#     correct_node_types(nodes)
#     ensure_connected(nodes)
#     write_swc(output_file, nodes)
#     print(f"规范化后的SWC文件已保存至：{output_file}")
#     # 收集所有父节点为胞体节点的节点信息
#     reparented_nodes = []
#     for node in nodes.values():
#         if node['P'] == soma_node and node['n'] != soma_node:
#             # 修改 reparented_nodes 的字段名
#             reparented_nodes.append({'n': node['n'], 'x': node['x'], 'y': node['y'], 'z': node['z'], 'radius': node['radius']})
#     if reparented_nodes:
#         write_marker(marker_file, reparented_nodes)
#         print(f"父节点为胞体节点的节点信息已保存至：{marker_file}")
#     else:
#         print("没有父节点为胞体节点的节点，未生成marker文件。")

if __name__ == "__main__":
    # input_file = r"D:\GXQ\cross_em_lm\test_data\em_33\out_1333261412_min10.swc"
    input_dir=r"D:\GXQ\cross_em_lm\test_data\test_34"
    output_dir = r"D:\GXQ\cross_em_lm\test_data\test_34"
    min_branch_len = 10  # 10 到 70，每隔 10 一次
    for file in os.listdir(input_dir):
        if not (str(os.path.basename(file)).endswith("out.swc")):
            input_file= os.path.join(input_dir,os.path.basename(file))
            cc=str(input_file).rstrip(".swc")
            output_file=f"{cc}_out22.swc"
            marker_file=f"{cc}_out.marker"
            standardize_swc(input_file, output_file, marker_file, min_branch_len)
    # 存储结果文件路径
    # output_files = []
    # marker_files = []
    # #逐个处理 min_branch_len
    # for min_branch_len in min_branch_lengths:
    #     output_file = f"{output_dir}\out_1333261412_min{min_branch_len}.swc"
    #     marker_file = f"{output_dir}\marker_1333261412_min{min_branch_len}.marker"

        # 调用函数
        # standardize_swc(input_file, output_file, marker_file, min_branch_len)

        # 记录生成的文件
        # output_files.append(output_file)
        # marker_files.append(marker_file)

    # # 可视化结果
    # fig, axes = plt.subplots(1, 7, figsize=(20, 3))
    #
    # for idx, min_branch_len in enumerate(min_branch_lengths):
    #     ax = axes[idx]
    #
    #     # 在这里添加你的代码，读取 `output_file` 中的数据并可视化
    #     # 这里假设你的 `visualize_swc` 函数可以将 .swc 文件加载并绘制
    #     output_file = output_files[idx]
    #     visualize_swc(output_file, ax)  # visualize_swc 是假设的可视化函数
    #
    #     ax.set_title(f"Min {min_branch_len}")
    #     ax.axis("off")  # 隐藏坐标轴
    #
    # plt.tight_layout()
    # plt.show()