import os


def read_swc(filename):
    nodes = {}
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) != 7:
                print(f"警告：行格式不正确，已忽略：{line}")
                continue
            n = int(parts[0])
            T = int(parts[1])
            x = float(parts[2])
            y = float(parts[3])
            z = float(parts[4])
            radius = float(parts[5])
            P = int(float(parts[6]))
            nodes[n] = {'n': n, 'T': T, 'x': x, 'y': y, 'z': z, 'radius': radius, 'P': P, 'children': [],
                        'modified': False}

    for node in nodes.values():
        P = node['P']
        if P != -1 and P in nodes:
            nodes[P]['children'].append(node['n'])
        elif P != -1:
            print(f"警告：父节点{P}不存在，节点{node['n']}的父节点设为-1")
            node['P'] = -1
    return nodes


def write_swc(filename, nodes):
    with open(filename, 'w') as f:
        f.write("# 标准化后的SWC文件\n")
        for n in sorted(nodes.keys()):
            node = nodes[n]
            T = 2 if node['modified'] else node['T']  # 修改过的节点T值设为2
            f.write(f"{node['n']} {T} {node['x']} {node['y']} {node['z']} {node['radius']} {node['P']}\n")


def write_marker(filename, markers):
    with open(filename, 'w') as f:
        f.write("# Marker file generated by standardize_swc.py\n")
        f.write("# n x y z radius\n")
        for marker in markers:
            f.write(f"{marker['n']} {marker['x']} {marker['y']} {marker['z']} {marker['radius']}\n")


def find_potential_soma(nodes):
    x_avg = sum(node['x'] for node in nodes.values()) / len(nodes)
    y_avg = sum(node['y'] for node in nodes.values()) / len(nodes)
    z_avg = sum(node['z'] for node in nodes.values()) / len(nodes)

    max_score = -1
    potential_soma = None
    for node in nodes.values():
        degree = len(node['children']) + (1 if node['P'] != -1 else 0)
        dx = node['x'] - x_avg
        dy = node['y'] - y_avg
        dz = node['z'] - z_avg
        distance = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
        score = (degree * node['radius']) / (1 + distance)

        if score > max_score:
            max_score = score
            potential_soma = node['n']

    return potential_soma


def rebuild_tree_from_soma(nodes, soma_node):
    nodes[soma_node]['P'] = -1
    visited = set()

    def dfs_update_parent(node_id):
        visited.add(node_id)
        current_node = nodes[node_id]

        for child_id in current_node['children']:
            if child_id not in visited:
                nodes[child_id]['P'] = node_id
                nodes[child_id]['modified'] = True  # 标记为已修改
                dfs_update_parent(child_id)

    dfs_update_parent(soma_node)

    for node in nodes.values():
        if node['P'] == -1 and node['n'] != soma_node:
            print(f"警告：节点 {node['n']} 未找到有效连接，保持孤立状态")


def prune_small_branches(nodes, min_branch_length, soma_node):
    nodes_to_delete = []
    for node_id in list(nodes.keys()):
        node = nodes[node_id]
        if node_id == soma_node or node['P'] == soma_node:
            continue
        if len(node['children']) == 0:
            branch_nodes = [(node_id, 0)]
            current_node_id = node_id
            branch_length = 0
            depth = 0
            while True:
                parent_id = nodes[current_node_id]['P']
                if parent_id == -1 or parent_id == soma_node:
                    break
                dx = nodes[current_node_id]['x'] - nodes[parent_id]['x']
                dy = nodes[current_node_id]['y'] - nodes[parent_id]['y']
                dz = nodes[current_node_id]['z'] - nodes[parent_id]['z']
                branch_length += (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
                current_node_id = parent_id
                depth += 1
                branch_nodes.append((current_node_id, depth))
                if len(nodes[parent_id]['children']) > 1:
                    break
            if branch_length < min_branch_length:
                nodes_to_delete.extend(branch_nodes)
    nodes_to_delete.sort(key=lambda x: x[1], reverse=True)
    for node_id, _ in nodes_to_delete:
        if node_id in nodes:
            parent_id = nodes[node_id]['P']
            if parent_id != -1 and parent_id in nodes and node_id in nodes[parent_id]['children']:
                nodes[parent_id]['children'].remove(node_id)
            nodes[node_id]['modified'] = True  # 标记被删除节点为已修改
            del nodes[node_id]
    print(f"已删除 {len(nodes_to_delete)} 个节点")


def remove_cycles(nodes):
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    visited = set()
    stack = [(soma_node, set())]
    while stack:
        node_id, ancestors = stack.pop()
        if node_id in visited:
            continue
        visited.add(node_id)
        if node_id in ancestors:
            print(f"检测到循环：节点{node_id}在其祖先中出现")
            nodes[node_id]['P'] = soma_node
            nodes[soma_node]['children'].append(node_id)
            nodes[node_id]['modified'] = True  # 标记为已修改
            continue
        ancestors.add(node_id)
        for child_id in nodes[node_id]['children'][:]:
            stack.append((child_id, ancestors.copy()))
        ancestors.remove(node_id)


def correct_node_types(nodes):
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    stack = [(soma_node, 1)]
    visited = set()
    while stack:
        node_id, parent_type = stack.pop()
        if node_id in visited:
            continue
        visited.add(node_id)
        node = nodes[node_id]
        if node['n'] == soma_node:
            node['T'] = 1
        else:
            node['T'] = 3 if node['P'] == soma_node else parent_type
        for child_id in node['children']:
            stack.append((child_id, node['T']))


def ensure_connected(nodes):
    soma_node = [node for node in nodes.values() if node['T'] == 1][0]
    soma_id = soma_node['n']
    connected_nodes = set()
    stack = [soma_id]
    while stack:
        current_node_id = stack.pop()
        if current_node_id in connected_nodes:
            continue
        connected_nodes.add(current_node_id)
        current_node = nodes[current_node_id]
        for child_id in current_node['children']:
            stack.append(child_id)
        parent_id = current_node['P']
        if parent_id != -1 and parent_id in nodes:
            stack.append(parent_id)

    unconnected_nodes = set(nodes.keys()) - connected_nodes
    for node_id in list(unconnected_nodes):
        node = nodes[node_id]
        dx = node['x'] - soma_node['x']
        dy = node['y'] - soma_node['y']
        dz = node['z'] - soma_node['z']
        distance = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
        if (node['P'] == -1 and len(node['children']) == 0) or (node['P'] == -1 and distance > 25):
            del nodes[node_id]
            print(f"已删除未连接到胞体且距离超过25的孤立点 {node_id}")


def standardize_swc(input_file, output_file, marker_file, min_branch_len):
    nodes = read_swc(input_file)
    if not nodes:
        print("错误：无法读取SWC文件或文件为空")
        return

    # 找到胞体节点并将其标记为 T == 1
    soma_node = find_potential_soma(nodes)
    if soma_node is not None:
        nodes[soma_node]['T'] = 1
    else:
        print("错误：未能识别出胞体节点")
        return

    rebuild_tree_from_soma(nodes, soma_node)
    prune_small_branches(nodes, min_branch_length=min_branch_len, soma_node=soma_node)
    remove_cycles(nodes)
    correct_node_types(nodes)
    ensure_connected(nodes)
    remove_cycles(nodes)
    reparented_nodes = []
    # 将所有未被修改的节点的 T 值设置为 4，但保留胞体节点为 T = 1
    for node in nodes.values():
        if not node['modified'] and node['n'] != soma_node:
            node['T'] = 4
        if node['n'] == soma_node:
            reparented_nodes.append(
                        {'n': node['n'], 'x': node['x'], 'y': node['y'], 'z': node['z'], 'radius': node['radius']})
            if reparented_nodes:
                write_marker(marker_file, reparented_nodes)
                print(f"父节点为胞体节点的节点信息已保存至：{marker_file}")
            else:
                print("没有父节点为胞体节点的节点，未生成marker文件。")

    write_swc(output_file, nodes)


if __name__ == "__main__":
    input_file = r"D:\GXQ\cross_em_lm\test_data\em_33\out_1333261412_min10.swc"
    input_dir=r"D:\GXQ\cross_em_lm\test_data\test_36"
    output_dir = r"D:\GXQ\cross_em_lm\test_data\test_35"
    min_branch_len = 10  # 10 到 70，每隔 10 一次
    for file in os.listdir(input_dir):
        if not (str(os.path.basename(file)).endswith("out.swc")):
            input_file= os.path.join(input_dir,os.path.basename(file))
            cc=str(input_file).rstrip(".swc")
            output_file=f"{cc}_out.swc"
            marker_file=f"{cc}_out.marker"
            standardize_swc(input_file, output_file, marker_file, min_branch_len)
    # input_file = r"D:\GXQ\cross_em_lm\test_data\test_35\46649875211.swc"
    # output_file = r"D:\GXQ\cross_em_lm\test_data\test_35\46649875211_out.swc"
    # marker_file = r"D:\GXQ\cross_em_lm\test_data\test_35\46649875211_out.marker"
    # standardize_swc(input_file, output_file, marker_file, 10)