#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

def read_swc(filename):
    nodes = {}
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            # 忽略空行和注释行
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) != 7:
                print(f"警告：行格式不正确，已忽略：{line}")
                continue
            n = int(parts[0])
            T = int(parts[1])
            x = float(parts[2])
            y = float(parts[3])
            z = float(parts[4])
            R = float(parts[5])
            P = int(float(parts[6]))
            nodes[n] = {'n': n, 'T': T, 'x': x, 'y': y, 'z': z, 'R': R, 'P': P, 'children': []}
    # 构建子节点列表
    for node in nodes.values():
        P = node['P']
        if P != -1 and P in nodes:
            nodes[P]['children'].append(node['n'])
        elif P != -1:
            print(f"警告：父节点{P}不存在，节点{node['n']}的父节点设为-1")
            node['P'] = -1
    return nodes

def write_swc(filename, nodes):
    with open(filename, 'w') as f:
        # 可在文件头添加注释
        f.write("# 标准化后的SWC文件\n")
        for n in sorted(nodes.keys()):
            node = nodes[n]
            f.write(f"{node['n']} {node['T']} {node['x']} {node['y']} {node['z']} {node['R']} {node['P']}\n")

def write_marker(filename, markers):
    with open(filename, 'w') as f:
        # 写入marker文件头
        f.write("# Marker file generated by standardize_swc.py\n")
        f.write("# n x y z radius\n")
        for marker in markers:
            f.write(f"{marker['n']} {marker['x']} {marker['y']} {marker['z']} {marker['R']}\n")

def compute_node_degrees(nodes):
    # 计算每个节点的度（连接数）
    for node in nodes.values():
        degree = len(node['children'])
        if node['P'] != -1:
            degree += 1  # 加上父节点
        node['degree'] = degree

def find_potential_soma(nodes):
    compute_node_degrees(nodes)
    max_degree = -1
    potential_soma = None
    for node in nodes.values():
        if node['degree'] > max_degree:
            max_degree = node['degree']
            potential_soma = node['n']
    return potential_soma

def adjust_soma_and_roots(nodes):
    # 检查是否存在类型为1的节点
    soma_nodes = [node['n'] for node in nodes.values() if node['T'] == 1]
    if soma_nodes:
        soma_node = soma_nodes[0]
        print(f"已找到胞体节点：{soma_node}")
    else:
        # 选择潜在的胞体节点
        soma_node = find_potential_soma(nodes)
        print(f"未找到胞体节点，选择节点{soma_node}作为胞体")
        nodes[soma_node]['T'] = 1
    # 将胞体节点的父节点设为-1
    nodes[soma_node]['P'] = -1
    # 清空胞体节点的子节点列表，重新构建
    nodes[soma_node]['children'] = []
    # 处理其他根节点
    for node in nodes.values():
        if node['P'] == -1 and node['n'] != soma_node:
            node['P'] = soma_node
            nodes[soma_node]['children'].append(node['n'])
            print(f"节点{node['n']}的父节点设为胞体节点{nodes[soma_node]['n']}")
        elif node['P'] == soma_node and node['n'] != soma_node:
            nodes[soma_node]['children'].append(node['n'])

def remove_cycles(nodes):
    # 检测并消除循环，使用迭代的DFS
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    visited = set()
    stack = [(soma_node, set())]  # Stack elements are (node_id, ancestors)
    while stack:
        node_id, ancestors = stack.pop()
        if node_id in visited:
            continue
        visited.add(node_id)
        if node_id in ancestors:
            print(f"检测到循环：节点{node_id}在其祖先中出现")
            # 断开循环，将该节点连接到胞体
            nodes[node_id]['P'] = soma_node
            nodes[soma_node]['children'].append(node_id)
            continue
        ancestors.add(node_id)
        for child_id in nodes[node_id]['children'][:]:
            stack.append((child_id, ancestors.copy()))
        ancestors.remove(node_id)

def correct_node_types(nodes):
    # 根据连接关系校正节点类型
    def dfs(node_id, parent_type, visited):
        if node_id in visited:
            return
        visited.add(node_id)
        node = nodes[node_id]
        if node['T'] == 1:
            # 已经是胞体，不修改
            pass
        else:
            node['T'] = parent_type
        for child_id in node['children']:
            dfs(child_id, node['T'], visited)
    # 从胞体节点开始遍历
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    visited = set()
    for child_id in nodes[soma_node]['children']:
        nodes[child_id]['T'] = 3  # 直接连接到胞体的设为树突（类型3）
        dfs(child_id, nodes[child_id]['T'], visited)

def ensure_connected(nodes):
    # 确保所有节点都连接到胞体
    visited = set()
    def dfs(node_id):
        if node_id in visited:
            return
        visited.add(node_id)
        for child_id in nodes[node_id]['children']:
            dfs(child_id)
    # 从胞体节点开始遍历
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    dfs(soma_node)
    # 查找未访问的节点
    for node_id in nodes:
        if node_id not in visited:
            print(f"节点{node_id}未连接到胞体，修正其父节点为胞体")
            nodes[node_id]['P'] = soma_node
            nodes[soma_node]['children'].append(node_id)

def standardize_swc(input_file, output_file, marker_file):
    nodes = read_swc(input_file)
    if not nodes:
        print("错误：无法读取SWC文件或文件为空")
        return
    adjust_soma_and_roots(nodes)
    remove_cycles(nodes)
    correct_node_types(nodes)
    ensure_connected(nodes)
    write_swc(output_file, nodes)
    print(f"规范化后的SWC文件已保存至：{output_file}")
    # 收集所有父节点为胞体节点的节点信息
    soma_node = [node['n'] for node in nodes.values() if node['T'] == 1][0]
    reparented_nodes = []
    for node in nodes.values():
        if node['P'] == soma_node and node['n'] != soma_node:
            reparented_nodes.append({'n': node['n'], 'x': node['x'], 'y': node['y'], 'z': node['z'], 'R': node['R']})
    if reparented_nodes:
        write_marker(marker_file, reparented_nodes)
        print(f"父节点为胞体节点的节点信息已保存至：{marker_file}")
    else:
        print("没有父节点为胞体节点的节点，未生成marker文件。")

# if __name__ == "__main__":
#     if len(sys.argv) != 4:
#         print("用法：python standardize_swc.py 输入文件.swc 输出文件.swc 输出marker文件.marker")
#     else:
#         # 增加递归深度限制，如有必要
#         sys.setrecursionlimit(10000)
#         input_file = sys.argv[1]
#         output_file = sys.argv[2]
#         marker_file = sys.argv[3]
#         standardize_swc(input_file, output_file, marker_file)

if __name__ == "__main__":
    # if len(sys.argv) != 4:
    #     print("用法：python standardize_swc.py 输入文件.swc 输出文件.swc 输出marker文件.marker")
    # else:
    #     # 增加递归深度限制，如有必要
    #     sys.setrecursionlimit(10000)
    #     input_file = sys.argv[1]
    #     output_file = sys.argv[2]
    #     marker_file = sys.argv[3]
    #     standardize_swc(input_file, output_file, marker_file)
    input_file = r"D:\GXQ\cross_em_lm\test_data\em_h01\1333261412.swc"
    output_file = r"D:\GXQ\cross_em_lm\test_data\em_h01\out_1333261412.swc"
    marker_file= r"D:\GXQ\cross_em_lm\test_data\em_h01\marker_1333261412.marker"
    standardize_swc(input_file, output_file,marker_file)
